import type { LearningPlanDetailDocument, LearningPlanListDocument } from "./types";

export const demoLearningPlanListDocument: LearningPlanListDocument = {
  source: "DEVELOPMENT_FIXTURE",
  date: "2026-08-21",
  weekdayEnglish: "Friday",
  weekdayChinese: "星期五",
  lunarDate: "丙午年 七月初九",
  weekStart: "2026-08-17",
  weekEnd: "2026-08-23",
  serviceState: "LEARNING_PLAN_LIST_SERVICE_UNAVAILABLE",
  plans: [
    {
      id: "fixture-plan-math-current",
      source: "DEVELOPMENT_FIXTURE",
      subjectCode: "MATH",
      subjectLabel: "数学",
      title: "二次函数图像学习计划",
      supportingLabel: "第 21 章 · 21.2 二次函数的图像",
      status: "CURRENT",
      startsOn: "2026-08-21",
      endsOn: "2026-08-23",
      completedOn: null,
      completedItems: 2,
      totalItems: 5,
      estimatedMinutes: 60,
      remainingMinutes: 42,
      serverConfirmation: "UNAVAILABLE",
    },
    {
      id: "fixture-plan-chinese-upcoming",
      source: "DEVELOPMENT_FIXTURE",
      subjectCode: "CHINESE",
      subjectLabel: "语文",
      title: "《桃花源记》阅读与赏析",
      supportingLabel: "",
      status: "UPCOMING",
      startsOn: "2026-08-22",
      endsOn: null,
      completedOn: null,
      completedItems: 0,
      totalItems: 3,
      estimatedMinutes: 45,
      remainingMinutes: null,
      serverConfirmation: "UNAVAILABLE",
    },
    {
      id: "fixture-plan-english-upcoming",
      source: "DEVELOPMENT_FIXTURE",
      subjectCode: "ENGLISH",
      subjectLabel: "英语",
      title: "Unit 6 Reading & Grammar",
      supportingLabel: "",
      status: "UPCOMING",
      startsOn: "2026-08-23",
      endsOn: null,
      completedOn: null,
      completedItems: 0,
      totalItems: 3,
      estimatedMinutes: 40,
      remainingMinutes: null,
      serverConfirmation: "UNAVAILABLE",
    },
    {
      id: "fixture-plan-history-completed",
      source: "DEVELOPMENT_FIXTURE",
      subjectCode: "HISTORY",
      subjectLabel: "历史",
      title: "明清时期的社会变化",
      supportingLabel: "",
      status: "COMPLETED_IN_CURRENT_SESSION",
      startsOn: "2026-08-20",
      endsOn: null,
      completedOn: "2026-08-20",
      completedItems: 4,
      totalItems: 4,
      estimatedMinutes: 30,
      remainingMinutes: null,
      serverConfirmation: "PENDING",
    },
  ],
};

export const demoLearningPlanDetailDocument: LearningPlanDetailDocument = {
  source: "DEVELOPMENT_FIXTURE",
  planId: "fixture-plan-math-current",
  courseId: "demo-course-math-7-autumn",
  lessonId: "fixture-lesson-math-21-2",
  subjectCode: "MATH",
  subjectLabel: "数学",
  title: "二次函数图像学习计划",
  chapterLabel: "第 21 章",
  lessonLabel: "21.2 二次函数的图像",
  status: "IN_PROGRESS",
  startsOn: "2026-08-21",
  endsOn: "2026-08-23",
  completedItems: 2,
  totalItems: 5,
  currentItemNumber: 3,
  totalMinutes: 60,
  usedMinutes: 18,
  remainingMinutes: 42,
  goal: "完成 21.2 二次函数图像课时，能够判断开口方向、对称轴与顶点，独立完成五题练习，并写下个人归纳。完成标准包括练习提交、必要订正与三条个人归纳。",
  basisExplanation: "先建立图像特征，再通过例题、独立练习和个人归纳形成完整学习顺序。",
  basisRows: [
    { label: "年级与学科", value: "演示配置", tone: "default" },
    { label: "课程位置", value: "21.2 当前课时", tone: "default" },
    { label: "今日顺序", value: "当前优先", tone: "default" },
    { label: "独立证据", value: "尚未产生", tone: "warning" },
  ],
  items: [
    {
      id: "fixture-plan-item-lesson-goal",
      number: 1,
      title: "阅读课时目标",
      description: "确认本课目标和学习顺序",
      estimatedMinutes: 5,
      state: "COMPLETED_IN_CURRENT_SESSION",
      targetView: "LESSON_DETAIL",
    },
    {
      id: "fixture-plan-item-knowledge-intro",
      number: 2,
      title: "知识导入",
      description: "认识开口、对称轴和顶点",
      estimatedMinutes: 13,
      state: "COMPLETED_IN_CURRENT_SESSION",
      targetView: "KNOWLEDGE_INTRO",
    },
    {
      id: "fixture-plan-item-worked-example",
      number: 3,
      title: "例题讲解",
      description: "从解析式和值表读出图像特征",
      estimatedMinutes: 15,
      state: "CURRENT",
      targetView: "WORKED_EXAMPLE",
    },
    {
      id: "fixture-plan-item-practice",
      number: 4,
      title: "随堂练习与订正",
      description: "提交 5 道练习，错误题完成订正",
      estimatedMinutes: 22,
      state: "PENDING",
      targetView: "PRACTICE",
    },
    {
      id: "fixture-plan-item-summary",
      number: 5,
      title: "归纳总结",
      description: "写下 3 条个人判断方法",
      estimatedMinutes: 5,
      state: "PENDING",
      targetView: "SUMMARY",
    },
  ],
  completionCriteria: [
    { id: "task-steps", label: "五项任务完成", currentValue: 2, totalValue: 5, status: "COUNT" },
    { id: "practice-submissions", label: "五道练习已提交", currentValue: 0, totalValue: 5, status: "COUNT" },
    { id: "mistake-correction", label: "错误题订正", currentValue: null, totalValue: null, status: "WAITING_FOR_PRACTICE" },
    { id: "personal-summary", label: "三条个人归纳", currentValue: 0, totalValue: 3, status: "COUNT" },
    { id: "learning-evidence", label: "学习证据", currentValue: null, totalValue: null, status: "WAITING_FOR_SERVICE" },
  ],
  serviceState: "LEARNING_PLAN_DETAIL_SERVICE_UNAVAILABLE",
  date: "2026-08-21",
  weekdayEnglish: "Friday",
  weekdayChinese: "星期五",
  lunarDate: "丙午年 七月初九",
};
