import type { TaskDetailDocument } from "./types";

export const demoTaskDetailDocument: TaskDetailDocument = {
  source: "DEVELOPMENT_FIXTURE",
  taskId: "a0000000-0000-4000-8000-000000000011",
  courseId: "demo-course-math-grade-8-spring",
  lessonId: "demo-lesson-math-21-2",
  priority: 1,
  totalPriorities: 4,
  subjectCode: "MATH",
  subjectLabel: "数学",
  title: "二次函数的图像与性质",
  textbookLabel: "人教版",
  gradeLabel: "初二下册",
  chapterLabel: "第 21 章",
  lessonLabel: "21.2 二次函数的图像",
  learningGoal: "理解并掌握二次函数图像的开口方向、对称轴与顶点坐标。",
  taskStatus: "IN_PROGRESS",
  currentStep: 2,
  totalSteps: 4,
  totalMinutes: 60,
  remainingMinutes: 42,
  rationale: "这项任务承接当前数学课程位置，先完成图像特征判断，再进入描点与实际应用。",
  rationaleBasis: "依据：本次演示中的课程位置与今日学习顺序。",
  rationaleCaveat: "仅用于演示任务排序，不代表真实掌握判断。",
  steps: [
    { id: "INTRO", number: 1, label: "知识导入", description: "认识开口、对称轴和顶点", state: "COMPLETED" },
    { id: "EXAMPLE", number: 2, label: "例题讲解", description: "从解析式读出图像特征", state: "CURRENT" },
    { id: "PRACTICE", number: 3, label: "随堂练习", description: "完成 5 道独立作答", state: "PENDING" },
    { id: "SUMMARY", number: 4, label: "归纳总结", description: "写下 3 条个人方法", state: "PENDING" },
  ],
  criteria: [
    { id: "learning-steps", label: "完成四个学习步骤", currentValue: 1, totalValue: 4, status: "IN_PROGRESS" },
    { id: "practice-submissions", label: "提交 5 道练习", currentValue: 0, totalValue: 5, status: "PENDING" },
    { id: "corrections", label: "错误题完成订正", currentValue: null, totalValue: null, status: "WAITING_FOR_PRACTICE" },
    { id: "personal-summaries", label: "写下 3 条个人归纳", currentValue: 0, totalValue: 3, status: "PENDING" },
  ],
  serviceState: "TASK_DETAIL_SERVICE_UNAVAILABLE",
  date: "2026-08-21",
  weekdayEnglish: "Friday",
  weekdayChinese: "星期五",
  lunarDate: "丙午年 七月初九",
};
