import type { PracticeDocument } from "./types";

export const demoPractice: PracticeDocument = {
  source: "DEVELOPMENT_FIXTURE",
  courseId: "demo-course-math-7-autumn",
  subjectCode: "MATH",
  subjectLabel: "数学",
  lessonLabel: "21.2 二次函数的图像",
  title: "随堂练习",
  subtitle: "独立作答，及时校验",
  date: "2026-08-22",
  weekdayChinese: "星期六",
  weekdayEnglish: "Saturday",
  estimatedMinutes: 15,
  steps: [
    { id: "INTRO", label: "知识导入", state: "COMPLETED" },
    { id: "EXAMPLE", label: "例题讲解", state: "COMPLETED" },
    { id: "PRACTICE", label: "随堂练习", state: "CURRENT" },
    { id: "SUMMARY", label: "归纳总结", state: "UPCOMING" },
  ],
  totalQuestions: 5,
  questions: [
    {
      kind: "MULTIPLE_CHOICE",
      id: "fixture-practice-q1",
      number: 1,
      typeLabel: "单项选择",
      skillLabel: "概念判断",
      stem: "已知二次函数 y = -2x² + 1，它的图像开口方向、对称轴和顶点分别是？",
      options: [
        { id: "A", label: "开口向上；对称轴 x = 0；顶点 (0,1)" },
        { id: "B", label: "开口向下；对称轴 x = 0；顶点 (0,1)" },
        { id: "C", label: "开口向下；对称轴 x = 1；顶点 (1,0)" },
        { id: "D", label: "开口向上；对称轴 x = 1；顶点 (1,0)" },
      ],
      answerKey: "B",
      explanation: [
        "二次项系数 -2 小于 0，所以图像开口向下。",
        "函数没有一次项，对称轴为 x = 0。",
        "当 x = 0 时，y = 1，因此顶点为 (0,1)。",
      ],
    },
    {
      kind: "NUMERIC_INPUT",
      id: "fixture-practice-q2",
      number: 2,
      typeLabel: "数值输入",
      skillLabel: "代入计算",
      stem: "当 x = 2 时，二次函数 y = -2x² + 1 的函数值是多少？",
      supportText: "请将 x 的值代入解析式，完成计算后只填写最终数值。",
      answerKey: -7,
      calculationCharacterLimit: 300,
      explanation: [
        "2² = 4。",
        "-2 × 4 = -8。",
        "-8 + 1 = -7。",
      ],
      hintOne: "先计算 2²，再将结果乘以 -2，最后加 1。",
      hintTwo: "注意先算乘方，再做乘法，最后做加法，并保留负号。",
    },
    {
      kind: "GRAPH_CHOICE",
      id: "fixture-practice-q3",
      number: 3,
      typeLabel: "图像识别",
      skillLabel: "图像匹配",
      stem: "下面哪一幅图像与二次函数 y = (x - 1)² - 1 相符？",
      supportText: "先判断开口方向，再比较对称轴和顶点位置。",
      options: [
        {
          id: "A",
          label: "选项 A",
          formula: "y = (x - 1)² - 1",
          plot: { a: 1, h: 1, k: -1, xMin: -3.5, xMax: 3.5, yMin: -3.5, yMax: 4.5 },
          accessibleDescription: "选项 A：一条开口向上的抛物线，对称轴为 x 等于 1，顶点位于 1、负 1。",
          feedback: {
            title: "图像判断正确",
            message: "开口方向、对称轴与顶点位置均与解析式一致。",
            openingDirection: "CORRECT_RETAINED",
            symmetryAxis: "CORRECT_RETAINED",
            vertexPosition: "CORRECT_RETAINED",
          },
        },
        {
          id: "B",
          label: "选项 B",
          formula: "y = -(x - 1)² - 1",
          plot: { a: -1, h: 1, k: -1, xMin: -3.5, xMax: 3.5, yMin: -3.5, yMax: 4.5 },
          accessibleDescription: "选项 B：一条开口向下的抛物线，对称轴为 x 等于 1，顶点位于 1、负 1。",
          feedback: {
            title: "再看开口方向",
            message: "重新观察二次项系数 a 的正负；对称轴和顶点判断可以保留。",
            openingDirection: "NEEDS_RETHINK",
            symmetryAxis: "CORRECT_RETAINED",
            vertexPosition: "CORRECT_RETAINED",
          },
        },
        {
          id: "C",
          label: "选项 C",
          formula: "y = (x + 1)² - 1",
          plot: { a: 1, h: -1, k: -1, xMin: -3.5, xMax: 3.5, yMin: -3.5, yMax: 4.5 },
          accessibleDescription: "选项 C：一条开口向上的抛物线，对称轴为 x 等于负 1，顶点位于负 1、负 1。",
          feedback: {
            title: "再看水平平移",
            message: "重新判断 (x - 1) 对对称轴和顶点横坐标的影响。",
            openingDirection: "CORRECT_RETAINED",
            symmetryAxis: "NEEDS_RETHINK",
            vertexPosition: "NEEDS_RETHINK",
          },
        },
        {
          id: "D",
          label: "选项 D",
          formula: "y = (x - 1)² + 1",
          plot: { a: 1, h: 1, k: 1, xMin: -3.5, xMax: 3.5, yMin: -3.5, yMax: 4.5 },
          accessibleDescription: "选项 D：一条开口向上的抛物线，对称轴为 x 等于 1，顶点位于 1、1。",
          feedback: {
            title: "再看垂直平移",
            message: "重新判断表达式末尾 -1 对顶点纵坐标的影响。",
            openingDirection: "CORRECT_RETAINED",
            symmetryAxis: "CORRECT_RETAINED",
            vertexPosition: "NEEDS_RETHINK",
          },
        },
      ],
      answerKey: "A",
      explanation: [
        "二次项系数 a = 1 大于 0，所以抛物线开口向上。",
        "解析式中的 x - 1 表示对称轴为 x = 1。",
        "表达式末尾为 -1，所以顶点为 (1,-1)。",
      ],
      hintOne: "先把函数与 y = a(x-h)² + k 对照，分别判断 a、h 和 k。",
      hintTwo: "按开口方向、对称轴、顶点的顺序逐项比较；仍不要直接猜选项字母。",
    },
    {
      kind: "COORDINATE_PLOT",
      id: "fixture-practice-q4-coordinate-plot",
      number: 4,
      typeLabel: "描点绘图",
      skillLabel: "函数图像",
      stem: "根据函数 y = x² − 2x − 3 的值表，在坐标系中描出对应点，并连接成平滑曲线。",
      instruction: "先逐个描点；全部点位确认后，再连接曲线。",
      functionExpression: "y = x² − 2x − 3",
      valueTable: [
        { x: -1, y: 0 },
        { x: 0, y: -3 },
        { x: 1, y: -4 },
        { x: 2, y: -3 },
        { x: 3, y: 0 },
      ],
      axis: { xMin: -3, xMax: 5, yMin: -6, yMax: 4, step: 1 },
      requiredPointCount: 5,
      snapStep: 1,
      symmetryNote: "x = 0 与 x = 2；x = −1 与 x = 3",
      answerPoints: [
        { x: -1, y: 0 },
        { x: 0, y: -3 },
        { x: 1, y: -4 },
        { x: 2, y: -3 },
        { x: 3, y: 0 },
      ],
      hintOne: "先按值表逐列核对 x 与 y，再把每一组数看作一个坐标点。",
      hintTwo: "检查成对点的函数值是否相同，再确认五个点都已落在整数网格上。",
    },
    {
      kind: "STRUCTURED_APPLICATION",
      id: "fixture-practice-q5-structured-application",
      number: 5,
      typeLabel: "结构化作答",
      skillLabel: "实际应用",
      stem: "某拱门的轮廓可近似表示为 y = −(x − 2)² + 4（单位：米），其中 x 轴表示地面。请完成最高点、地面交点和拱门宽度的判断，并用一句话说明依据。",
      scenario: "某拱门的轮廓可近似表示为 y = −(x − 2)² + 4（单位：米），其中 x 轴表示地面。请完成最高点、地面交点和拱门宽度的判断，并用一句话说明依据。",
      instruction: "按顺序填写；所有必填项完成后才能提交。",
      functionExpression: "y = −(x − 2)² + 4",
      explanationMaxLength: 120,
      hintOne: "先区分最高点、地面交点和宽度分别表示什么。",
      hintTwo: "最高点可以从函数的顶点形式判断；地面交点对应 y = 0。",
      answerKey: {
        vertexX: 2,
        vertexY: 4,
        interceptX1: 0,
        interceptX2: 4,
        width: 4,
      },
    },
  ],
  hintOne: "先观察二次项系数的正负，它决定抛物线的开口方向。",
  hintTwo: "将函数与 y = a(x-h)² + k 对照，分别判断 a、h 和 k。",
};
