import type { LessonFlowCompletionDocument } from "./types";

export const demoLessonComplete: LessonFlowCompletionDocument = {
  source: "DEVELOPMENT_FIXTURE",
  courseId: "demo-course-math-7-autumn",
  lessonId: "fixture-lesson-complete-math-21-2",
  subjectCode: "MATH",
  subjectLabel: "数学",
  lessonLabel: "21.2 二次函数的图像",
  title: "本课完成",
  subtitle: "方法已整理，后续结果等待确认",
  date: "2026-08-22",
  weekdayChinese: "星期六",
  weekdayEnglish: "Saturday",
  steps: [
    { id: "INTRO", label: "知识导入", state: "COMPLETED" },
    { id: "EXAMPLE", label: "例题讲解", state: "COMPLETED" },
    { id: "PRACTICE", label: "随堂练习", state: "COMPLETED" },
    { id: "SUMMARY", label: "归纳总结", state: "COMPLETED" },
  ],
  completionTitle: "本课页面流程已完成",
  completionDescription: "你已完成知识导入、例题讲解、五题练习和个人归纳。",
  completionTruth: "当前会话完成不等于云端保存、学习证据或掌握度已由服务端确认。",
  methodSteps: [
    { id: "OPENING", number: 1, title: "看开口", description: "" },
    { id: "AXIS_VERTEX", number: 2, title: "找轴与顶点", description: "" },
    { id: "PLOT", number: 3, title: "描点成图", description: "" },
    { id: "VERIFY", number: 4, title: "核对特征", description: "" },
  ],
  methodContextNote: "遇到实际情境时，再把顶点、交点和距离还原为题目中的含义。",
  pageStepsCompleted: 4,
  totalPageSteps: 4,
  currentSessionState: "PAGE_FLOW_COMPLETED",
  serverLessonCompletion: "NOT_SUBMITTED",
  cloudSummarySave: "UNAVAILABLE",
  evidenceConfirmation: "PENDING",
  mistakeConfirmation: "PENDING",
  masteryConfirmation: "UNCHANGED",
  practiceSubmittedQuestions: 5,
  recoveredAfterHint: 1,
  pendingExplanationReview: 1,
  personalSummaries: [
    { id: "OPENING", number: 1, text: "先看二次项系数 a 的正负，判断图像开口向上还是向下。", sessionState: "COMPLETED_IN_CURRENT_SESSION" },
    { id: "AXIS_VERTEX", number: 2, text: "再从顶点式读出 h、k，或通过计算确定对称轴与顶点。", sessionState: "COMPLETED_IN_CURRENT_SESSION" },
    { id: "PLOT_VERIFY", number: 3, text: "选择对称的 x 值描点，再检查顶点、对称性和交点是否一致。", sessionState: "COMPLETED_IN_CURRENT_SESSION" },
  ],
  localReviewRecommendation: "2_TO_3_DAYS",
  reviewRecommendationText: "建议在 2–3 天后重新判断一组二次函数图像，并独立完成一次描点。",
  officialReviewSchedule: "PENDING",
  serviceState: "LESSON_COMPLETION_SERVICE_UNAVAILABLE",
};
